runtime: custom
env: flex

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.13"

entrypoint: streamlit run streamlit_app.py --server.port $PORT

automatic_scaling:
  max_num_instances: 1
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: ""

build_env_variables:
  GOOGLE_BUILD_TIMEOUT: "30m"
  PIP_NO_CACHE_DIR: "1"